### ISSUE TITLE
Модератор-2

### ISSUE THREAD

**Issue by R3621** [helphubteam/helphub#68]
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

**Проблема, которую мы хотим решить:**
В фонде 16 координаторов. Им всем нужно создавать просьбы и координировать просьбы, поэтому им выдадут права Модераторов
При добавлении новых волонтеров они будут получать об этом письма и будут иметь возможность их одобрить. 
Это неудобно, тк порождает бардак, в чем мы убедились на примере тестового фонда.

**Решение, которое мы решили реализовать**
Ввести роль Модератор-2, у которого будет меньше прав, чем у обычного модератора. См. таблицу с правами.
Модератор-2 - условное название, нужно придумать лучше.

- Права Модератору-2 выдаются там же, где и права волонтеру и модератору
- Т.к Модератор-2 не сможет редактировать настройки организации и типы просьб, эти пункты меню можно вообще от него скрыть

<meta http-equiv="Content-Style-Type" content="text/css">
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2022.6">
</head>
<body>

№ | Действие | Админ | Модератор | Модератор-2 (новая роль) | Волонтер
-- | -- | -- | -- | -- | --
1 | Создавать просьбы |   |   |   | НЕТ
2 | Редактировать свои просьбы |   |   |   | НЕТ
3 | Редактировать просьбы, которые создали другие координаторы |   |   | НЕТ | НЕТ
4 | Смотреть свои просьбы |   |   |   | НЕТ
5 | Смотреть просьбы, которые создали другие координаторы |   |   | Пока нет | НЕТ
6 | Добавлять волонтеров |   |   | НЕТ | НЕТ
7 | Получать письма о подключении волонтеров (НЕ МОГУТ) |   |   | НЕТ | НЕТ
8 | Одобрять волонтеров |   |   | НЕТ | НЕТ
9 | Просматривать список волонтеров фонда |   |   |   | НЕТ
10 | Редактировать Виды просьб |   |   | НЕТ | НЕТ
11 | Редактировать настройки фонда |   |   | НЕТ | НЕТ
12 | Скачивать отчеты |   |   | Пока нет | НЕТ
13 | Логиниться в мобилку |   | НЕТ | НЕТ |  
14 | Просматривать профиль волонтера |   |   | НЕТ |  

</body>
</html>

**Comment by Allagri** [comment]
@lxkuz @R3621 
Нашла эту старую карточку и ...согласно Наташиной таблице  требований (см. выше) к Модератору-2, ныне Редактору просьб,
наш Редактор просьб:
1. (п. 12) Не может скачивать отчеты 
2. (п. 5) Не может смотреть просьбы, созданные другими координаторами: Модератором? др. Редакторами? - Наш Редактор видит только свои просьбы. 
3. (п. 9) ??? - Список волонтеров Редактор может видеть только в выпадающем комбике "Назначить волонтера на просьбу". Для этого надо как минимум зайти в просьбу и открыть этот комбик. 
Решение А: оставить только такую возможность просмотра волонтеров.
Решение Б: добавить вкладку Пользователи без возможности редактирования. 

Или мы 1) выкатываем в ближайшем релизе имеющийся уже вариант,  а  потом доделываем в соответствии с требованиями ИЛИ 2) доделываем, согласно требованиям ИЛИ 3) ?

**Comment by R3621** [comment]
@Allagri - мы обсуждали раньше, что выбираем вариант 3) - правим табличку в соответсвии с реализацией. Я закрою тогда задачку?
