### ISSUE TITLE
translation missing: ru.devise.sessions.user.already_signed_out

### ISSUE THREAD

**Issue by Allagri** [helphubteam/helphub#69]
![IMG_20210902_230022](https://user-images.githubusercontent.com/81861260/131908615-dafa6dd0-f3a0-4c2e-ad52-4b8c23892d41.jpg)
1. Admin открывает админку в двух вкладках. 
2. Закрывает приложение в одной вкладке -> Cообщение: Выход из системы выполнен.
3. Закрывает приложение во второй вкладке -> **Сообщение: translation missing: ru.devise.sessions.user.already_signed_out** (СМ. скриншот)
@lxkuz - это по твоей части

**Comment by zavialova** [comment]
Проверено в staging. Нет замечаний
