### ISSUE TITLE
Дополнительные поля на stage/new располагаются в разной очередности

### ISSUE THREAD

**Issue by Allagri** [helphubteam/helphub#80]
![сравнение](https://user-images.githubusercontent.com/81861260/132767591-be1463d5-a0bc-48ef-8e66-e9977b698e69.PNG)
- какая очередность верна?

**Comment by R3621** [comment]
Верна очередность, в которой дополнительные поля идут раньше, чем волонтёр и баллы 
Фонд просил нас так сделать, потому что дополнительные поля они используют чаще
