### ISSUE TITLE
Доп. поле типа "Телефон" не отображается у волонтера ни в разделе "Все просьбы", ни в разделе "Мои просьбы"

### ISSUE THREAD

**Issue by Allagri** [helphubteam/helphub#83]
1. Создать новую просьбу
2. В "Дополнительные поля" выбрать вид просьбы test -> открываются все поля этого вида просьбы
3. Заполнить поле СОТОВЫЙ ПОЛУЧАТЕЛЯ (публичное поле) ->cохранить
4. Посмотреть отображение данной просьбы у волонтера в разделе "Все просьбы". **Ожидаемый результат**: поле видно у волонтера в разделе ВСЕ ПРОСЬБЫ, т.к. является публичным.
5. Волонтер берет просьбу в работу -> открывает эту же просьбу в разделе МОИ ПРОСЬБЫ. **Ожидаемый резуль**тат: поле СОТОВЫЙ ПОЛУЧАТЕЛЯ отображаееся. 
6. **Реальный результат:** Поле типа "телефон" не отображается ни в одном разделе.

**Comment by lxkuz** [comment]
интересная проблема связана с тем что в базе нашлись дубликаты custom_value записи. Я не понял каким образом они создались но я добавил валидацию чтобы впредь это избежать
https://github.com/helphubteam/helphub/pull/84

**Comment by Allagri** [comment]
Протестировано, замечаний нет.
