### ISSUE TITLE
Невозможно создать новый вид просьбы

### ISSUE THREAD

**Issue by Allagri** [helphubteam/helphub#86]
![невозможно сохранить новый вид просьбы](https://user-images.githubusercontent.com/81861260/133509782-8baa9f60-71e0-47b2-83a5-4b8890af61d5.PNG)
Также не понятно, какие ошибки обнаружены, т.к. ничего не подсвечено (см. скрин)

Функция - Вносить изменения в имеющиеся просьбы и сохранять их -  **работает**.

**Уточнение**: возможно создание нового вида просьбы **БЕЗ** каких либо полей. При создании хотя бы одного поля возникает ошибка, как на скриншоте выше.

**Comment by lxkuz** [comment]
@Allagri  эту поправил тем что запретил добавление полей при создании вида просьб

**Comment by Allagri** [comment]
Проверено. Отдельно создается вид просьбы, после сохранения добавляются необходимые поля.
